---
- name: upload jdk1.7
  copy: src=jdk-7u79-linux-x64.rpm dest={{dest_dir}} owner=root group=root mode=644
  tags: tomcat

- name: be sure jdk1.7 installed
  yum: pkg=/usr/local/src/jdk-7u79-linux-x64.rpm state=installed
  tags: tomcat

- name: upload or sync tomcat-native
  copy: src=tomcat-native-1.1.33-src.tar.gz dest={{dest_dir}}
  tags: tomcat

- name: upload or sync tomcat1.7
  copy: src=apache-tomcat-7.0.63.tar.gz dest={{dest_dir}}
  tags: tomcat

- name: Extract tomcat1.7 
  shell: chdir={{dest_dir}}  tar zxvf apache-tomcat-7.0.63.tar.gz -C /usr/local 
  tags: tomcat

- name: Extract tomcat-native
  command: chdir={{dest_dir}}  tar zxvf tomcat-native-1.1.33-src.tar.gz
  tags: tomcat

- name: install directory
  shell: chdir=/usr/local rm -rf tomcat && mv apache-tomcat-7.0.63 tomcat
  tags: tomcat

- name: install tomcat-native scripts
  copy: src=install_native.sh dest={{dest_dir}}/tomcat-native-1.1.33-src/jni/native mode=655
  tags: tomcat

- name: install tomcat-natvie
  shell: chdir={{dest_dir}}/tomcat-native-1.1.33-src/jni/native  ./install_native.sh >> /dev/null
  tags: tomcat

- name: isntall tomcat started script
  copy: src=tomcat dest=/etc/init.d/ mode=0755
  tags: tomcat

- name: add tomcat script to service
  service: name=tomcat enabled=yes
  tags: tomcat
